#FROM openjdk
#WORKDIR usr/lib
#ENV MONGO_DATABASE="usercontent"
#ENV MONGO_URL="mongodb://localhost:27017/usercontent"
#ADD ./target/UserServices-0.0.1-SNAPSHOT.jar /usr/lib/UserServices-0.0.1-SNAPSHOT.jar
#ENTRYPOINT ["java","-jar","UserServices-0.0.1-SNAPSHOT.jar"]