version: "3.9"
services:
  mysql-farms:
    image: mysql:latest
    container_name: mysql-farms
    networks:
      - proxy
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongocontainer:

    container_name: mongocontainer
    image: mongo:latest
    networks:
      - proxy
    ports:
      - "27017:27017"


  user-auth-service:
    image: user-auth-service-image
    container_name: user-auth-service
    build: UserRegistration/
    networks:
      - proxy
    ports:
      - "8086:8086"
    depends_on:
      - mysql-farms
      - api-gateway-service
      - eureka-service


    restart: always

  user-service:
    image: user-service-image
    container_name: user-service
    build: UserServices/
    networks:
      - proxy
    ports:
      - "8087:8087"
    depends_on:
      - mongocontainer
      - api-gateway-service
      - eureka-service



  api-gateway-service:
    image:   api-gateway-service-image
    container_name: api-gateway-service
    build: ApiGateway/
    networks:
      - proxy
    ports:
      - "9500:9500"
    depends_on:
      - eureka-service

  eureka-service:
    image: eureka-image
    container_name: eureka-service
    build: Eureka-server/
    restart: always
    environment:
      EUREKA_SERVER_PORT: 8761
    networks:
      - proxy
    ports:
      - "8761:8761"


networks:
  proxy:
    driver: bridge